$(document).ready(function () {
    $("#demo1_B").hide()
    $("#demo1_A").hover(function () {
        $("#demo1_B").toggle()
        $("#demo1_A").toggle()
    });
    $("#demo2_B").hide()
    $("#demo2_A").hover(function () {
        $("#demo2_B").toggle()
        $("#demo2_A").toggle()
    });
    $("#demo3_B").hide()
    $("#demo3_A").hover(function () {
        $("#demo3_B").toggle()
        $("#demo3_A").toggle()
    });
    $("#demo4_B").hide()
    $("#demo4_A").hover(function () {
        $("#demo4_B").toggle()
        $("#demo4_A").toggle()
    });
    $("#demo5_B").hide()
    $("#demo5_A").hover(function () {
        $("#demo5_B").toggle()
        $("#demo5_A").toggle()
    });
    $("#demo6_B").hide()
    $("#demo6_A").hover(function () {
        $("#demo6_B").toggle()
        $("#demo6_A").toggle()
    });
    $("#demo7_B").hide()
    $("#demo7_A").hover(function () {
        $("#demo7_B").toggle()
        $("#demo7_A").toggle()
    });
    $("#demo8_B").hide()
    $("#demo8_A").hover(function () {
        $("#demo8_B").toggle()
        $("#demo8_A").toggle()
    });
    $("#all").click(function(){
        $("#demo1_B").toggle()
        $("#demo1_A").toggle()
        $("#demo2_B").toggle()
        $("#demo2_A").toggle()
        $("#demo3_B").toggle()
        $("#demo3_A").toggle()
        $("#demo4_B").toggle()
        $("#demo4_A").toggle()
        $("#demo5_B").toggle()
        $("#demo5_A").toggle()
        $("#demo6_B").toggle()
        $("#demo6_A").toggle()
        $("#demo7_B").toggle()
        $("#demo7_A").toggle()
        $("#demo8_B").toggle()
        $("#demo8_A").toggle()
    });
    $("#all-building").click(function(){
        $("#demo2_B").toggle()
        $("#demo2_A").toggle()
        $("#demo7_B").toggle()
        $("#demo7_A").toggle()
    });
    $("#all-finance").click(function(){
        $("#demo3_B").toggle()
        $("#demo3_A").toggle()
        $("#demo5_B").toggle()
        $("#demo5_A").toggle()
        $("#demo4_B").toggle()
        $("#demo4_A").toggle()
    });
    $("#all-business").click(function(){
        $("#demo1_B").toggle()
        $("#demo1_A").toggle()
        $("#demo6_B").toggle()
        $("#demo6_A").toggle()
        $("#demo8_B").toggle()
        $("#demo8_A").toggle()
    });
    $(".card-hide_0").hide()
    $(".card-hide_0").click(function(){
        $("#facebook-img_0").show()
        $(".card-hide_0").hide()
    });
    $("#facebook-img_0").click(function(){
        $(".card-hide_0").show()
    });
    $(".card-hide_1").hide()
    $(".card-hide_1").click(function(){
        $("#facebook-img_1").show()
        $(".card-hide_1").hide()
    });
    $("#facebook-img_1").click(function(){
        $(".card-hide_1").show()
    });
    $(".card-hide_2").hide()
    $(".card-hide_2").click(function(){
        $("#facebook-img_2").show()
        $(".card-hide_2").hide()
    });
    $("#facebook-img_2").click(function(){
        $(".card-hide_2").show()
    });
    $(".card-hide_3").hide()
    $(".card-hide_3").click(function(){
        $("#facebook-img_3").show()
        $(".card-hide_3").hide()
    });
    $("#facebook-img_3").click(function(){
        $(".card-hide_3").show()
    });
    $('#play_video').dblclick(function(){
        $('#video_1')[0].play();
        $("#play_video").hide()
    });
    $("video").click(function(){
        $("#play_video").show()
    });
    $("#play_video").click(function(){
        $('#video_1')[0].pause();
    });
    $(".content_01").hide()
    $("#img-01").click(function () {
        $(".content_01").show()
        $("#img-01").hide()
    });
    $(".content_01").click(function () {
        $("#img-01").show()
        $(".content_01").hide()
    });
    $("#page-1").click(function(){
        $(".page_1").show()
        $(".page_2").hide()
    });
    $(".page_2").hide()
    $("#page-2").click(function(){
        $(".page_2").show()
        $(".page_1").hide()
    });
});
